'use client';

import { useState } from 'react';
import { Sparkles, ChevronDown, ChevronUp } from 'lucide-react';

interface AISummaryProps {
  summary: string;
  keyTakeaways?: string[];
}

export function AISummary({ summary, keyTakeaways }: AISummaryProps) {
  const [isExpanded, setIsExpanded] = useState(true);

  if (!summary) return null;

  return (
    <div className="my-6 rounded-lg overflow-hidden border border-purple-500/20 bg-gradient-to-br from-purple-500/5 to-blue-500/5 not-prose">
      {/* Header */}
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-purple-500/5 transition-colors"
      >
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-md bg-purple-500/10">
            <Sparkles className="h-4 w-4 text-purple-500" />
          </div>
          <span className="text-sm font-semibold text-foreground">AI Summary</span>
          <span className="text-xs px-2 py-0.5 rounded-full bg-purple-500/10 text-purple-600 dark:text-purple-400 font-medium">
            Auto-generated
          </span>
        </div>
        {isExpanded ? (
          <ChevronUp className="h-4 w-4 text-muted-foreground" />
        ) : (
          <ChevronDown className="h-4 w-4 text-muted-foreground" />
        )}
      </button>

      {/* Content */}
      {isExpanded && (
        <div className="px-4 pb-4 space-y-4">
          {/* Summary */}
          <p className="text-sm text-foreground/90 leading-relaxed">
            {summary}
          </p>

          {/* Key Takeaways */}
          {keyTakeaways && keyTakeaways.length > 0 && (
            <div className="pt-3 border-t border-purple-500/10">
              <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">
                Key Takeaways
              </h4>
              <ul className="space-y-1.5">
                {keyTakeaways.map((takeaway, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm text-foreground/90">
                    <span className="text-purple-500 mt-1">•</span>
                    <span>{takeaway}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Disclaimer */}
          <p className="text-xs text-muted-foreground italic pt-2">
            This summary was generated by AI and may not capture all nuances of the original post.
          </p>
        </div>
      )}
    </div>
  );
}
